version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "8001:8001"
    links:
      - "server"

  server:
    build: ./blog-backend
    ports:
      - "31090:31090"
    volumes:
      - ./blog-backend:/go/src/sandbox-server
    container_name: "server"

  db:
    build: ./db
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/data:/data/db
      - ./db/mongo/configdb:/data/configdb
    container_name: "db"

  client:
    build: ./nuxt-grpc-blog
    ports:
      - "8080:8080"
    links:
      - "server"